language: ruby
sudo: false

services:
  - redis-server

cache: bundler

env:
  - REDIS_NAMESPACE="wtf"
  - REDIS_NAMESPACE=""

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.1
matrix:
  fast_finish: true
  include:
    - rvm: 2.4
      env: TEST_SUITE="rubocop"

before_install:
  - gem update --system
  - gem --version
  - gem install bundler --no-rdoc --no-ri
  - bundle --version

install: bundle install --without development doc

script: bundle exec rake $TEST_SUITE
